In [1]:
import numpy as np
import pandas as pd
import re
import nltk
import spacy
import string

In [2]:
full_df = pd.read_csv('/content/drive/MyDrive/ML AI/Session 23 NLP/1429_1.csv', nrows=5000)
full_df

,id,name,asins,brand,categories,keys,manufacturer,reviews.date,reviews.dateAdded,reviews.dateSeen,...,reviews.doRecommend,reviews.id,reviews.numHelpful,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username
0,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,This product so far has not disappointed. My c...,Kindle,NaN,NaN,Adapter
1,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,great for beginner or experienced person. Boug...,very fast,NaN,NaN,truman
2,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.,NaN,NaN,DaveZ
3,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,4.0,http://reviews.bestbuy.com/3545/5620406/review...,I've had my Fire HD 8 two weeks now and I love...,Good!!!,NaN,NaN,Shacks
4,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-12T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,I bought this for my grand daughter when she c...,Fantastic Tablet for kids,NaN,NaN,explore42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,AVphgVaX1cnluZ0-DR74,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B018Y229OU,Amazon,"Fire Tablets,Tablets,Computers & Tablets,All T...",firetablet7displaywifi8gbincludesspecialoffers...,Amazon,2016-07-07T00:00:00.000Z,2017-05-21T02:57:54Z,"2017-04-30T00:20:00.000Z,2017-06-07T08:18:00.000Z",...,True,NaN,0.0,4.0,http://reviews.bestbuy.com/3545/5025800/review...,Amazing tablet for the price i love it is real...,Great tablet,NaN,NaN,spawnevil
4996,AVphgVaX1cnluZ0-DR74,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B018Y229OU,Amazon,"Fire Tablets,Tablets,Computers & Tablets,All T...",firetablet7displaywifi8gbincludesspecialoffers...,Amazon,2016-07-08T00:00:00.000Z,2017-05-21T02:57:42Z,"2017-04-30T00:20:00.000Z,2017-06-07T08:18:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5025800/review...,I love my fire... The games and the pictures g...,fire,NaN,NaN,chef
4997,AVphgVaX1cnluZ0-DR74,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B018Y229OU,Amazon,"Fire Tablets,Tablets,Computers & Tablets,All T...",firetablet7displaywifi8gbincludesspecialoffers...,Amazon,2016-07-08T00:00:00.000Z,2017-05-21T02:57:42Z,"2017-04-30T00:20:00.000Z,2017-06-07T08:18:00.000Z",...,False,NaN,1.0,1.0,http://reviews.bestbuy.com/3545/5025800/review...,Great tablet for kids but the screen isn't as ...,Fire,NaN,NaN,John
4998,AVphgVaX1cnluZ0-DR74,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B018Y229OU,Amazon,"Fire Tablets,Tablets,Computers & Tablets,All T...",firetablet7displaywifi8gbincludesspecialoffers...,Amazon,2016-07-08T00:00:00.000Z,2017-05-21T02:57:42Z,"2017-04-30T00:20:00.000Z,2017-06-07T08:18:00.000Z",...,True,NaN,0.0,4.0,http://reviews.bestbuy.com/3545/5025800/review...,Great product easy to use. Having different co...,kindle,NaN,NaN,queque
4999,AVphgVaX1cnluZ0-DR74,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B018Y229OU,Amazon,"Fire Tablets,Tablets,Computers & Tablets,All T...",firetablet7displaywifi8gbincludesspecialoffers...,Amazon,2016-07-08T00:00:00.000Z,2017-05-21T02:57:42Z,"2017-04-30T00:20:00.000Z,2017-06-07T08:18:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5025800/review...,"Love this tablet, great price and is really fa...",Love it,NaN,NaN,Newhome

In [3]:
df = full_df[["reviews.text","reviews.title"]]
df

,reviews.text,reviews.title
0,This product so far has not disappointed. My c...,Kindle
1,great for beginner or experienced person. Boug...,very fast
2,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.
3,I've had my Fire HD 8 two weeks now and I love...,Good!!!
4,I bought this for my grand daughter when she c...,Fantastic Tablet for kids
...,...,...
4995,Amazing tablet for the price i love it is real...,Great tablet
4996,I love my fire... The games and the pictures g...,fire
4997,Great tablet for kids but the screen isn't as ...,Fire
4998,Great product easy to use. Having different co...,kindle
4999,"Love this tablet, great price and is really fa...",Love it

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   reviews.text   4999 non-null   object
 1   reviews.title  4999 non-null   object
dtypes: object(2)
memory usage: 78.2+ KB

#Lowercasing

In [5]:
df["reviews.title"] = df["reviews.title"].astype(str)
df["reviews.text"] = df["reviews.text"].astype(str)

<ipython-input-5-3cad09c96c40>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["reviews.title"] = df["reviews.title"].astype(str)
<ipython-input-5-3cad09c96c40>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["reviews.text"] = df["reviews.text"].astype(str)

In [6]:
df["reviews.title"] = df["reviews.title"].str.lower()
df["reviews.text"] = df["reviews.text"].str.lower()
df.head()

<ipython-input-6-0999e20d6b9e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["reviews.title"] = df["reviews.title"].str.lower()
<ipython-input-6-0999e20d6b9e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["reviews.text"] = df["reviews.text"].str.lower()

,reviews.text,reviews.title
0,this product so far has not disappointed. my c...,kindle
1,great for beginner or experienced person. boug...,very fast
2,inexpensive tablet for him to use and learn on...,beginner tablet for our 9 year old son.
3,i've had my fire hd 8 two weeks now and i love...,good!!!
4,i bought this for my grand daughter when she c...,fantastic tablet for kids

#Removing Punctuation

In [7]:
import string
string.punctuation
def remove_punct(text):
    text_nopunct = "".join([char for char in text if char not in string.punctuation])
    return text_nopunct


df["reviews.title_clean"] = df["reviews.title"].apply(lambda x: remove_punct(x))
df["reviews.text_clean"] = df["reviews.text"].apply(lambda x: remove_punct(x))

df.head()

<ipython-input-7-c22e53a55cc6>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["reviews.title_clean"] = df["reviews.title"].apply(lambda x: remove_punct(x))
<ipython-input-7-c22e53a55cc6>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["reviews.text_clean"] = df["reviews.text"].apply(lambda x: remove_punct(x))

,reviews.text,reviews.title,reviews.title_clean,reviews.text_clean
0,this product so far has not disappointed. my c...,kindle,kindle,this product so far has not disappointed my ch...
1,great for beginner or experienced person. boug...,very fast,very fast,great for beginner or experienced person bough...
2,inexpensive tablet for him to use and learn on...,beginner tablet for our 9 year old son.,beginner tablet for our 9 year old son,inexpensive tablet for him to use and learn on...
3,i've had my fire hd 8 two weeks now and i love...,good!!!,good,ive had my fire hd 8 two weeks now and i love ...
4,i bought this for my grand daughter when she c...,fantastic tablet for kids,fantastic tablet for kids,i bought this for my grand daughter when she c...

#Tokenization

In [8]:
import re

def tokenize(text):
    tokens = re.split('\W+', text)
    return tokens

df['reviews.title_tokenized'] = df['reviews.title_clean'].apply(lambda x: tokenize(x.lower()))

df['reviews.text_tokenized'] = df['reviews.text_clean'].apply(lambda x: tokenize(x.lower()))

df.head()

<ipython-input-8-39ce9e4e53e3>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviews.title_tokenized'] = df['reviews.title_clean'].apply(lambda x: tokenize(x.lower()))
<ipython-input-8-39ce9e4e53e3>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviews.text_tokenized'] = df['reviews.text_clean'].apply(lambda x: tokenize(x.lower()))

,reviews.text,reviews.title,reviews.title_clean,reviews.text_clean,reviews.title_tokenized,reviews.text_tokenized
0,this product so far has not disappointed. my c...,kindle,kindle,this product so far has not disappointed my ch...,[kindle],"[this, product, so, far, has, not, disappointe..."
1,great for beginner or experienced person. boug...,very fast,very fast,great for beginner or experienced person bough...,"[very, fast]","[great, for, beginner, or, experienced, person..."
2,inexpensive tablet for him to use and learn on...,beginner tablet for our 9 year old son.,beginner tablet for our 9 year old son,inexpensive tablet for him to use and learn on...,"[beginner, tablet, for, our, 9, year, old, son]","[inexpensive, tablet, for, him, to, use, and, ..."
3,i've had my fire hd 8 two weeks now and i love...,good!!!,good,ive had my fire hd 8 two weeks now and i love ...,[good],"[ive, had, my, fire, hd, 8, two, weeks, now, a..."
4,i bought this for my grand daughter when she c...,fantastic tablet for kids,fantastic tablet for kids,i bought this for my grand daughter when she c...,"[fantastic, tablet, for, kids]","[i, bought, this, for, my, grand, daughter, wh..."


#Remove Stopwords

In [9]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [10]:
from nltk.corpus import stopwords
", ".join(stopwords.words('english'))

"i, me, my, myself, we, our, ours, ourselves, you, you're, you've, you'll, you'd, your, yours, yourself, yourselves, he, him, his, himself, she, she's, her, hers, herself, it, it's, its, itself, they, them, their, theirs, themselves, what, which, who, whom, this, that, that'll, these, those, am, is, are, was, were, be, been, being, have, has, had, having, do, does, did, doing, a, an, the, and, but, if, or, because, as, until, while, of, at, by, for, with, about, against, between, into, through, during, before, after, above, below, to, from, up, down, in, out, on, off, over, under, again, further, then, once, here, there, when, where, why, how, all, any, both, each, few, more, most, other, some, such, no, nor, not, only, own, same, so, than, too, very, s, t, can, will, just, don, don't, should, should've, now, d, ll, m, o, re, ve, y, ain, aren, aren't, couldn, couldn't, didn, didn't, doesn, doesn't, hadn, hadn't, hasn, hasn't, haven, haven't, isn, isn't, ma, mightn, mightn't, mustn, mustn't, needn, needn't, shan, shan't, shouldn, shouldn't, wasn, wasn't, weren, weren't, won, won't, wouldn, wouldn't"

In [11]:
STOPWORDS = set(stopwords.words('english'))
def remove_stopwords(text):
    """custom function to remove the stopwords"""
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])


df['reviews.title_stopwords'] = df['reviews.title_clean'].apply(lambda text: remove_stopwords(text))
df['reviews.text_stopwords'] = df['reviews.text_clean'].apply(lambda text: remove_stopwords(text))
df.head()

<ipython-input-11-09676f15c801>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviews.title_stopwords'] = df['reviews.title_clean'].apply(lambda text: remove_stopwords(text))
<ipython-input-11-09676f15c801>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviews.text_stopwords'] = df['reviews.text_clean'].apply(lambda text: remove_stopwords(text))

,reviews.text,reviews.title,reviews.title_clean,reviews.text_clean,reviews.title_tokenized,reviews.text_tokenized,reviews.title_stopwords,reviews.text_stopwords
0,this product so far has not disappointed. my c...,kindle,kindle,this product so far has not disappointed my ch...,[kindle],"[this, product, so, far, has, not, disappointe...",kindle,product far disappointed children love use lik...
1,great for beginner or experienced person. boug...,very fast,very fast,great for beginner or experienced person bough...,"[very, fast]","[great, for, beginner, or, experienced, person...",fast,great beginner experienced person bought gift ...
2,inexpensive tablet for him to use and learn on...,beginner tablet for our 9 year old son.,beginner tablet for our 9 year old son,inexpensive tablet for him to use and learn on...,"[beginner, tablet, for, our, 9, year, old, son]","[inexpensive, tablet, for, him, to, use, and, ...",beginner tablet 9 year old son,inexpensive tablet use learn step nabi thrille...
3,i've had my fire hd 8 two weeks now and i love...,good!!!,good,ive had my fire hd 8 two weeks now and i love ...,[good],"[ive, had, my, fire, hd, 8, two, weeks, now, a...",good,ive fire hd 8 two weeks love tablet great valu...
4,i bought this for my grand daughter when she c...,fantastic tablet for kids,fantastic tablet for kids,i bought this for my grand daughter when she c...,"[fantastic, tablet, for, kids]","[i, bought, this, for, my, grand, daughter, wh...",fantastic tablet kids,bought grand daughter comes visit set user ent...

#Removal of Frequent words

In [12]:
from collections import Counter
cnt = Counter()
for text in df["reviews.title_stopwords"].values:
    for word in text.split():
        cnt[word] += 1


cnt.most_common(10)

[('great', 1813),
 ('tablet', 1363),
 ('good', 563),
 ('price', 434),
 ('love', 284),
 ('kindle', 281),
 ('product', 272),
 ('fire', 232),
 ('nice', 209),
 ('stars', 194)]

In [13]:
from collections import Counter
cnt = Counter()
for text in df["reviews.text_stopwords"].values:
    for word in text.split():
        cnt[word] += 1


cnt.most_common(10)

[('tablet', 2102),
 ('great', 1797),
 ('kindle', 1163),
 ('use', 1130),
 ('price', 960),
 ('good', 907),
 ('easy', 822),
 ('bought', 814),
 ('fire', 782),
 ('love', 751)]

#Stemming

In [14]:
from nltk.stem.porter import PorterStemmer

# Drop the two columns
#df.drop(["text_wo_stopfreq", "text_wo_stopfreqrare"], axis=1, inplace=True)

stemmer = PorterStemmer()
def stem_words(text):
    return " ".join([stemmer.stem(word) for word in text.split()])

df["reviews.text_stemmed"] = df["reviews.text_stopwords"].apply(lambda text: stem_words(text))
df["reviews.title_stemmed"] = df["reviews.title_stopwords"].apply(lambda text: stem_words(text))
df.head()

<ipython-input-14-d0968d4da575>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["reviews.text_stemmed"] = df["reviews.text_stopwords"].apply(lambda text: stem_words(text))
<ipython-input-14-d0968d4da575>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["reviews.title_stemmed"] = df["reviews.title_stopwords"].apply(lambda text: stem_words(text))

,reviews.text,reviews.title,reviews.title_clean,reviews.text_clean,reviews.title_tokenized,reviews.text_tokenized,reviews.title_stopwords,reviews.text_stopwords,reviews.text_stemmed,reviews.title_stemmed
0,this product so far has not disappointed. my c...,kindle,kindle,this product so far has not disappointed my ch...,[kindle],"[this, product, so, far, has, not, disappointe...",kindle,product far disappointed children love use lik...,product far disappoint children love use like ...,kindl
1,great for beginner or experienced person. boug...,very fast,very fast,great for beginner or experienced person bough...,"[very, fast]","[great, for, beginner, or, experienced, person...",fast,great beginner experienced person bought gift ...,great beginn experienc person bought gift love,fast
2,inexpensive tablet for him to use and learn on...,beginner tablet for our 9 year old son.,beginner tablet for our 9 year old son,inexpensive tablet for him to use and learn on...,"[beginner, tablet, for, our, 9, year, old, son]","[inexpensive, tablet, for, him, to, use, and, ...",beginner tablet 9 year old son,inexpensive tablet use learn step nabi thrille...,inexpens tablet use learn step nabi thrill lea...,beginn tablet 9 year old son
3,i've had my fire hd 8 two weeks now and i love...,good!!!,good,ive had my fire hd 8 two weeks now and i love ...,[good],"[ive, had, my, fire, hd, 8, two, weeks, now, a...",good,ive fire hd 8 two weeks love tablet great valu...,ive fire hd 8 two week love tablet great value...,good
4,i bought this for my grand daughter when she c...,fantastic tablet for kids,fantastic tablet for kids,i bought this for my grand daughter when she c...,"[fantastic, tablet, for, kids]","[i, bought, this, for, my, grand, daughter, wh...",fantastic tablet kids,bought grand daughter comes visit set user ent...,bought grand daughter come visit set user ente...,fantast tablet kid

#Lemmatization

In [15]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [16]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])



df["reviews.text_lemmaatized"] = df["reviews.text_stopwords"].apply(lambda text: lemmatize_words(text))
df["reviews.title_lemmatized"] = df["reviews.title_stopwords"].apply(lambda text: lemmatize_words(text))
df.head()

<ipython-input-16-a7a3b807dc73>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["reviews.text_lemmaatized"] = df["reviews.text_stopwords"].apply(lambda text: lemmatize_words(text))
<ipython-input-16-a7a3b807dc73>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["reviews.title_lemmatized"] = df["reviews.title_stopwords"].apply(lambda text: lemmatize_words(text))

,reviews.text,reviews.title,reviews.title_clean,reviews.text_clean,reviews.title_tokenized,reviews.text_tokenized,reviews.title_stopwords,reviews.text_stopwords,reviews.text_stemmed,reviews.title_stemmed,reviews.text_lemmaatized,reviews.title_lemmatized
0,this product so far has not disappointed. my c...,kindle,kindle,this product so far has not disappointed my ch...,[kindle],"[this, product, so, far, has, not, disappointe...",kindle,product far disappointed children love use lik...,product far disappoint children love use like ...,kindl,product far disappointed child love use like a...,kindle
1,great for beginner or experienced person. boug...,very fast,very fast,great for beginner or experienced person bough...,"[very, fast]","[great, for, beginner, or, experienced, person...",fast,great beginner experienced person bought gift ...,great beginn experienc person bought gift love,fast,great beginner experienced person bought gift ...,fast
2,inexpensive tablet for him to use and learn on...,beginner tablet for our 9 year old son.,beginner tablet for our 9 year old son,inexpensive tablet for him to use and learn on...,"[beginner, tablet, for, our, 9, year, old, son]","[inexpensive, tablet, for, him, to, use, and, ...",beginner tablet 9 year old son,inexpensive tablet use learn step nabi thrille...,inexpens tablet use learn step nabi thrill lea...,beginn tablet 9 year old son,inexpensive tablet use learn step nabi thrille...,beginner tablet 9 year old son
3,i've had my fire hd 8 two weeks now and i love...,good!!!,good,ive had my fire hd 8 two weeks now and i love ...,[good],"[ive, had, my, fire, hd, 8, two, weeks, now, a...",good,ive fire hd 8 two weeks love tablet great valu...,ive fire hd 8 two week love tablet great value...,good,ive fire hd 8 two week love tablet great value...,good
4,i bought this for my grand daughter when she c...,fantastic tablet for kids,fantastic tablet for kids,i bought this for my grand daughter when she c...,"[fantastic, tablet, for, kids]","[i, bought, this, for, my, grand, daughter, wh...",fantastic tablet kids,bought grand daughter comes visit set user ent...,bought grand daughter come visit set user ente...,fantast tablet kid,bought grand daughter come visit set user ente...,fantastic tablet kid

In [17]:
# Drop the two columns which are no more needed
df.drop(["reviews.title_clean","reviews.text_clean",	"reviews.title_tokenized",	"reviews.text_tokenized",	"reviews.title_stopwords",	"reviews.text_stopwords"], axis=1, inplace=True)

<ipython-input-17-86ba3205d3ac>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(["reviews.title_clean","reviews.text_clean",	"reviews.title_tokenized",	"reviews.text_tokenized",	"reviews.title_stopwords",	"reviews.text_stopwords"], axis=1, inplace=True)

In [18]:
df.head()

,reviews.text,reviews.title,reviews.text_stemmed,reviews.title_stemmed,reviews.text_lemmaatized,reviews.title_lemmatized
0,this product so far has not disappointed. my c...,kindle,product far disappoint children love use like ...,kindl,product far disappointed child love use like a...,kindle
1,great for beginner or experienced person. boug...,very fast,great beginn experienc person bought gift love,fast,great beginner experienced person bought gift ...,fast
2,inexpensive tablet for him to use and learn on...,beginner tablet for our 9 year old son.,inexpens tablet use learn step nabi thrill lea...,beginn tablet 9 year old son,inexpensive tablet use learn step nabi thrille...,beginner tablet 9 year old son
3,i've had my fire hd 8 two weeks now and i love...,good!!!,ive fire hd 8 two week love tablet great value...,good,ive fire hd 8 two week love tablet great value...,good
4,i bought this for my grand daughter when she c...,fantastic tablet for kids,bought grand daughter come visit set user ente...,fantast tablet kid,bought grand daughter come visit set user ente...,fantastic tablet kid

#Contractions Removal

In [19]:
!pip install contractions

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting contractions
  Downloading contractions-0.1.73-py2.py3-none-any.whl (8.7 kB)
Collecting textsearch>=0.0.21 (from contractions)
  Downloading textsearch-0.0.24-py2.py3-none-any.whl (7.6 kB)
Collecting anyascii (from textsearch>=0.0.21->contractions)
  Downloading anyascii-0.3.2-py3-none-any.whl (289 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 289.9/289.9 kB 5.8 MB/s eta 0:00:00
Collecting pyahocorasick (from textsearch>=0.0.21->contractions)
  Downloading pyahocorasick-2.0.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.8/110.8 kB 12.1 MB/s eta 0:00:00
Installing collected packages: pyahocorasick, anyascii, textsearch, contractions
Successfully installed anyascii-0.3.2 contractions-0.1.73 pyahocorasick-2.0.0 textsearch-0.0.24

In [20]:
import pandas as pd
import contractions

# Define the contraction expansion function
def expand_contractions(text):
    expanded_text = contractions.fix(text)
    return expanded_text

# Apply the expansion function to the 'text' column
df['reviews.text_contract'] = df['reviews.text_lemmaatized'].apply(expand_contractions)
df['reviews.title_contract'] = df['reviews.title_lemmatized'].apply(expand_contractions)
# Print the updated dataframe
df.head()

<ipython-input-20-05fed53da0b5>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviews.text_contract'] = df['reviews.text_lemmaatized'].apply(expand_contractions)
<ipython-input-20-05fed53da0b5>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviews.title_contract'] = df['reviews.title_lemmatized'].apply(expand_contractions)

,reviews.text,reviews.title,reviews.text_stemmed,reviews.title_stemmed,reviews.text_lemmaatized,reviews.title_lemmatized,reviews.text_contract,reviews.title_contract
0,this product so far has not disappointed. my c...,kindle,product far disappoint children love use like ...,kindl,product far disappointed child love use like a...,kindle,product far disappointed child love use like a...,kindle
1,great for beginner or experienced person. boug...,very fast,great beginn experienc person bought gift love,fast,great beginner experienced person bought gift ...,fast,great beginner experienced person bought gift ...,fast
2,inexpensive tablet for him to use and learn on...,beginner tablet for our 9 year old son.,inexpens tablet use learn step nabi thrill lea...,beginn tablet 9 year old son,inexpensive tablet use learn step nabi thrille...,beginner tablet 9 year old son,inexpensive tablet use learn step nabi thrille...,beginner tablet 9 year old son
3,i've had my fire hd 8 two weeks now and i love...,good!!!,ive fire hd 8 two week love tablet great value...,good,ive fire hd 8 two week love tablet great value...,good,i have fire hd 8 two week love tablet great va...,good
4,i bought this for my grand daughter when she c...,fantastic tablet for kids,bought grand daughter come visit set user ente...,fantast tablet kid,bought grand daughter come visit set user ente...,fantastic tablet kid,bought grand daughter come visit set user ente...,fantastic tablet kid

In [21]:
df.head()

,reviews.text,reviews.title,reviews.text_stemmed,reviews.title_stemmed,reviews.text_lemmaatized,reviews.title_lemmatized,reviews.text_contract,reviews.title_contract
0,this product so far has not disappointed. my c...,kindle,product far disappoint children love use like ...,kindl,product far disappointed child love use like a...,kindle,product far disappointed child love use like a...,kindle
1,great for beginner or experienced person. boug...,very fast,great beginn experienc person bought gift love,fast,great beginner experienced person bought gift ...,fast,great beginner experienced person bought gift ...,fast
2,inexpensive tablet for him to use and learn on...,beginner tablet for our 9 year old son.,inexpens tablet use learn step nabi thrill lea...,beginn tablet 9 year old son,inexpensive tablet use learn step nabi thrille...,beginner tablet 9 year old son,inexpensive tablet use learn step nabi thrille...,beginner tablet 9 year old son
3,i've had my fire hd 8 two weeks now and i love...,good!!!,ive fire hd 8 two week love tablet great value...,good,ive fire hd 8 two week love tablet great value...,good,i have fire hd 8 two week love tablet great va...,good
4,i bought this for my grand daughter when she c...,fantastic tablet for kids,bought grand daughter come visit set user ente...,fantast tablet kid,bought grand daughter come visit set user ente...,fantastic tablet kid,bought grand daughter come visit set user ente...,fantastic tablet kid